### ISSUE TITLE
I think TWA is not stable yet, till then we can launch PWA on error/exception

### ISSUE THREAD

**Issue by jitendra1607** [GoogleChrome/android-browser-helper#106]
I think TWA is not stable yet, it is crushing many times on different devices. We can have a workaround till this stabilize. We should catch any error and launch chrome browser with PWA link. This way users will get have something working.

**Comment by andreban** [comment]
From #94, you seem to be using custom-tabs-client, instead of android-browser-helper, which is probably the source of many of the stability issues you are seeing.

android-browser-helper already falls back to launching a Custom Tabs if Trusted Web Activity is not available and opening the default browser when Custom Tabs is not available. It's also possible to opt-in into a WebView fallback. 

Some issues can happen on the Android OS itself and, in those cases, it's impossible to launch the browser.

**Comment by jitendra1607** [comment]
Ok, i got it. I have check grade file and i am using android browser
helper. Should i post gradle content here?

**Comment by andreban** [comment]
#94 looks like the best place for it.
