### ISSUE TITLE
Violation of Families Policy Requirements

### ISSUE THREAD

**Issue by uditbh** [GoogleChrome/android-browser-helper#139]
Submitted my apk file to google play store after wrap my pwa with your twa library. My app got rejected on the following basis:

> Webviews:
We don't allow apps whose primary purpose is to provide a webview of a website, regardless of ownership, or to aggregate content that does not belong to the developer. To resolve this issue, please remove violating content and resubmit your app.

May I know the reason why I am facing this ?

**Comment by andreban** [comment]
When your app is designed primarily for children under 13, additional [Play Family policies](https://play.google.com/about/families/) apply, which may be incompatible with using Trusted Web Activity.  

This is highlighted in the documentation here: https://web.dev/using-a-pwa-in-your-android-app/#quality-criteria.

We're working on improving that and there's a discussion in this issue https://github.com/GoogleChromeLabs/svgomg-twa/issues/67. I'm closing the issue here so we can focus on the existing one.
