### ISSUE TITLE
Run foreground service for TWA app

### ISSUE THREAD

**Issue by jmgarbowski** [GoogleChrome/android-browser-helper#197]
Hi.
I use TWA to run a web application using WebRTC. I set up an audio connection (microphone access) and minimize the application to the background. On Android version 9 or higher I lose access to the microphone after a minute. Is there any way to start foreground service for TWA to keep access to the microphone and continue the conversation in this situation?

**Comment by PEConn** [comment]
What browser are you using? (I'm going to assume Chrome) And it's the web page that's requesting audio access? Or are you modifying the native side of the TWA?

Does the same thing happen if you open your page in Chrome and then background that? I'm trying to figure out whether this is the case of:

* Android killing your TWA.
* Android killing your Chrome.
* Chrome killing your TWA's tab.

**Comment by jmgarbowski** [comment]
Thanks for reply. Yes, it's Chrome in TWA and I don't modify anything in a native side of TWA. 

The scenario looks like this: I establish a webRTC connection in the web application launched in TWA, the conversation continues. I minimize TWA, after a minute when the application is in the background I lose access to the microphone. Neither chrome nor TWA is killed by Android. After returning to TWA from recent tasks the microphone works again. The requirement of this project is that the microphone should work all the time, even in the background. The user should be informed that the microphone records all the time. In the native application I would solve this through foreground service, unfortunately for TWA I do not know how to deal with it.
I believe that this case happens because of privacy changes in Android 9: 
https://www.xda-developers.com/android-p-audio-recording-limitations-privacy/

When I open the page in Chrome I have the same issue.

**Comment by PEConn** [comment]
So off the bat I'm not 100% sure what the solution to this could be, but what I'd try is:

1. Add a foreground service to your app.
2. Extend LauncherActivity.
3. Launch the foreground service in onStart.
4. Ensure you're using an Android Browser Helper alpha version so that you have [this change](https://github.com/GoogleChrome/android-browser-helper/commit/eb4766c11d16bea4b9f431dbc6c5cb8c51788e28#diff-52782b2596e8b60858f8913c0f8a5a28379aa2615c0346e13fc85f44008a65d1).

So hopefully now your app will have a Foreground service so you can keep recording *and* this will transitively apply to Chrome. (Though we aren't using [Context.BIND_INCLUDE_CAPABILITIES](https://developer.android.com/reference/android/content/Context#BIND_INCLUDE_CAPABILITIES), so maybe not.)

Ideally though there should be some way to make this work with Android side changes, I'll have an ask around.

**Comment by jmgarbowski** [comment]
Thanks, I'll check your solution today.

**Comment by jmgarbowski** [comment]
@PEConn thank you very much! It looks like beta version of TWA library does the job. I've used version 2.0.0 before and in this version does not contain mentioned [changes](https://github.com/GoogleChrome/android-browser-helper/commit/eb4766c11d16bea4b9f431dbc6c5cb8c51788e28#diff-52782b2596e8b60858f8913c0f8a5a28379aa2615c0346e13fc85f44008a65d1). The question is whether the developers intend to make these changes in a stable version?

**Comment by PEConn** [comment]
Yeah, we're hoping to bring the changes to stable channel. The reason it's not in stable at the moment is because it relies on an alpha/beta version of `androidx.browser`, and we don't want a stable version of our library to have an unstable dependency. Once `androidx.browser` gets to stable with the required change, Android Browser Helper will also do so.

**Comment by andreban** [comment]
The new `androidx.browser` version was released and this should be available on `android-browser-helper-2.2.0`.
