### ISSUE TITLE
open new a tab (url) inside of TWA by browser which is not inside of TWA

### ISSUE THREAD

**Issue by thanhtungka91** [GoogleChrome/android-browser-helper#239]
We are running our website inside of TWA but there are some pages that do not belong to our app so we want to open the link by google chrome browser (not inside of our TWA app).
I would like to know is it possible in TWA?

the original question is reported from  
https://github.com/GoogleChromeLabs/svgomg-twa/issues/112

**Comment by PEConn** [comment]
Hey,

There's no easy "open external links in the full browser" feature you can turn on. Funnily enough we'd never heard this request and then 4 or so different people have asked for it in quick succession. Do you mind sharing why you prefer this behaviour?

There is a more involved way of getting this behaviour though, make each of your of-origin links launch an Android Activity in your TWA that in turn launches Chrome. You can either do this using a custom scheme (my-twa-app://www.some-website.com) or using [Android Intent Links](https://developer.chrome.com/docs/multidevice/android/intents/). (The second one is a bit more involved but I think will mean you don't need any Android specific behaviour in your site/server).

**Comment by thanhtungka91** [comment]
Thank you very much for your quick reply and suggestions. I think the first one using a custom scheme seems a good idea because we can control the page.  

Yeah, there are some pages that do NOT belong to us (like the survey pages) so we want to let users aware that this page is external and not related to our services.

**Comment by glavrjk** [comment]
Regards. I would recommend that instead of looking to open a new link in another tab. Work directly on your application. Inserting the external content of your surveys (example) within an embedded modal. If you use frameworks in your html development, it is very easy to insert content from external urls into an html component.

```
<div id="my-hello-div" data-remote="https://www.helloexample.com">
        --- html html and more code
        <div id="my-hello-body">
        </div>
</div>

<script>
   $.get($(this).attr('data-remote'), function (data) {
            $("#my-hello-body").html(data);
            $('#my-hello-div').modal();
        });
</script>
```
Now, @PEConn I have a question for you. Is the [https://github.com/GoogleChromeLabs/svgomg-twa](url) project still advisable to use as a basis for creating new PWAs? what do you recommend? I used that project a while ago to create my first PWA and now I have to create a new one. Of course I had to modify certain things like the AndroidX and the obsolete components. But is it still advisable to clone it to start a new PWA?

**Comment by PEConn** [comment]
@glavrjk svgomg-twa is deprecated - you should use [bubblewrap](https://github.com/GoogleChromeLabs/bubblewrap) instead.
