### ISSUE TITLE
Location and notification doesn't work if host is not included in intent filter

### ISSUE THREAD

**Issue by onkar-rentomojo** [GoogleChrome/android-browser-helper#372]
**Describe the bug**
TWA android browser helper delegation service don't work when host is not added in intent filters. For Location I get the error as your location is blocked and in case of notifications, they come through chrome instead of TWA

**To Reproduce**
1. Don't add host in intent filter
2. Try accessing the location
3. See error

**Expected behavior**
User should be able to access the location and in case of notifications, they should come from notification delegation service instead of chrome

**Comment by PEConn** [comment]
This isn't a use case we support - your TWA should have intent filters for
your website.

**Comment by onkar-rentomojo** [comment]
We have intent filters for specific paths. Declaring just host will allow all the URLs to be opened in the app - which we don't want always.

**Comment by PEConn** [comment]
You could make your use case work by changing the intent filter to the whole host but then have LauncherActivity look at the Intent URL and just launch it in the browser in some cases. That would mostly work, but there may be some rough edges, for example if the user sees your app in the Android disambiguation prompt, clicks it and then are confused why the browser opens.

Otherwise, I'd say this is more of a feature request than a bug report as having an Intent filter for your entire origin is how TWAs were designed to work.

**Comment by EiraGe** [comment]
This issue should be fixed by crbug.com/1357825
