### ISSUE TITLE
Add docs for using this library.

### ISSUE THREAD

**Issue by PEConn** [GoogleChrome/android-browser-helper#9]

**Comment by andreban** [comment]
Adding the documentation depends on making the package available on a Package Registry. That's probably going to be JCenter and we are working to make it available there. Once it is, we'll update the docs with details on how to use it from JCenter.

**Comment by homer-jay** [comment]
Please, please update the readme with some information on how to add the dependency. This is the only supported way of using Chrome Custom Tabs with androidx. As far as I know we can't use the older appcompat method along with the newer androidx dependencies.
 
Also note that the samples in this repo are not helpful because:
1.  They depend on an older version of androidx.browser
2.  They use the gradle dependency as if the library was actually in the same root directory:
```
implementation project(path: ':androidbrowserhelper')
``` 
We need the full external repo URL (ideally from maven or jcenter), and some hint explaining that the androidx.browser dependency should also be added.

**Comment by andreban** [comment]
Added instructions on how to pull it from the Google Maven on #37

**Comment by andreban** [comment]
Closing this, as instructions have been added on #37
